version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306  
    networks:
      - twotier
    restart: always
    healthcheck:
      #ye container tab tak up nahi ho ga jab tak isk health check satisfied nahi ho jaty
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
    

  flask-app:
    build:
      #  context: .
      context: .
      dockerfile: ./Dockerfile-multistage
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: mydb
    networks:
      - twotier
    volumes:
      - flask-data:/app
    depends_on:
      - mysql
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
    restart: always
networks:
  twotier:
volumes:
  mysql-data:
  flask-data:

